name: build

on:
  push:
    branches: [ros, ros2, galactic-devel, foxy-devel, noetic-devel, melodic-devel, kinetic-devel]

  workflow_dispatch: # allow manually starting this workflow

jobs:
  matrix_preparation:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix-combinations }}
    steps:
    - name: Define matrix
      id: set-matrix
      run: |
        branch_name=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')

        if [ "$branch_name" == "galactic-devel" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "galactic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "focal", "ALLOW_FAIL": false},
          '
        elif [ "$branch_name" == "foxy-devel" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "foxy", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "focal", "ALLOW_FAIL": false},
          '
        elif [ "$branch_name" == "noetic-devel" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "noetic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "focal", "ALLOW_FAIL": false},
          '
        elif [ "$branch_name" == "melodic-devel" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "melodic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "bionic", "ALLOW_FAIL": false},
            {"ROS_DISTRO": "melodic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "stretch", "ALLOW_FAIL": true},
          '
        elif [ "$branch_name" == "kinetic-devel" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "kinetic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "xenial", "ALLOW_FAIL": true},
          '
        elif [ "$branch_name" == "ros2" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "galactic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "focal", "ALLOW_FAIL": false},
            {"ROS_DISTRO": "foxy", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "focal", "ALLOW_FAIL": false},
          '
        elif [ "$branch_name" == "ros" ]
        then
          MATRIX_PARAMS_COMBINATIONS='
            {"ROS_DISTRO": "noetic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "focal", "ALLOW_FAIL": false},
            {"ROS_DISTRO": "melodic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "bionic", "ALLOW_FAIL": false},
            {"ROS_DISTRO": "melodic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "stretch", "ALLOW_FAIL": true},
            {"ROS_DISTRO": "kinetic", "ROS_REPO": "testing", "OS_NAME": "ubuntu", "OS_CODE_NAME": "xenial", "ALLOW_FAIL": true},
          '
        fi
        
        echo ::set-output name=matrix-combinations::{\"env\":[$MATRIX_PARAMS_COMBINATIONS]}

  ros_ci:
    needs: matrix_preparation
    name: ROS ${{ matrix.env.ROS_DISTRO }} (${{ matrix.env.OS_CODE_NAME }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix_preparation.outputs.matrix)}}
    continue-on-error: ${{ matrix.env.ALLOW_FAIL }}
    env:
      UPSTREAM_WORKSPACE: "github:ros-naoqi/libqi#${{ matrix.env.ROS_DISTRO }}-devel"
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - name: Check out libqicore repo
        uses: actions/checkout@v2
      - name: Fetch/store directory used by ccache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-
      - name: Run industrial CI
        uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}